#CycleGAN default configs
batch_size: 2
num_workers: 2 #2021-4-26 worker进程数。worker负责将dataloader所需的batch提前送进ram，加快训练速度
use_gpu: True
checkpoints_dir: runs/ # a folder that records all the training and testing results
last_epoch: last
num_epochs: 1
print_step: 1
metrics_step: 1
window_size: 100 # the moving average window size for training and testing stats
visualize_step: 100 # number of batch iters to visualize cyclegan's outputs
save_step: 1 # number of epochs to snapshot the currently trained model
visual_window: [0.0, 1.0] # the pixel value window for CT image visualization
dataset: 
  dataset_type: nature_image
  nature_image:
    a_dir: "data/nature_image/train/artifact"
    b_dir: "data/nature_image/train/no_artifact"
    random_flip: True
    load_size: 384
    crop_size: 256
    a_range: [-1000.0, 2000.0]
    b_range: [-1000.0, 2000.0]
model:
  g_type: cyclegan
  d_type: nlayer
  cyclegan:
    input_ch: 1
    base_ch: 16
    num_down: 2 # number of downsampling (as well as upsampling) blocks
    num_residual: 2 # number of residual blocks
    num_sides: 2 # number of artifact encoding layers
    down_norm: instance
    res_norm: instance
    up_norm: layer
    fuse: True # if specified, fuse the artifact features with decoder features
    shared_decoder: False # if specified, artifact and non-artifact decoders are shared
  nlayer:
    input_nc: 1
    ndf: 16
    n_layers: 2
    norm_layer: instance
learn:
  lr: 1.e-4
  beta1: 0.5 # params for Adam optim
  beta2: 0.999 # params for Adam optim
  weight_decay: 1.e-4
  gamma: 0.5 # learning rate decay
  step_size: 1.e+5 # means no learning rate decay
loss:
  gt_art: True # use inputs instead of cyclegan's recon outputs for artifact consistency loss
  wgts: # loss weights. first element: loss type, second element: weight of the loss
    ll: [l1, 0.0] # recon loss (low)
    lh: [l1, 0.0] # set this to nonzero to train for paired data
    hh: [l1, 0.0] # recon loss (high) 
    lhl: [l1, 20.0] # self-artifact synthesis loss,cycleGAN loss 1
    hlh: [l1, 20.0] # self-reduction,cycleGAN loss 2
    art: [l1, 20.0] # artifact consistency loss
    gh: [gh, 1.0] # GAN loss for high
    gl: [gl, 1.0] # GAN loss for low
 